---
title: "Exploratory Analysis"
author: "Diana Ballesteros"
date: "10/4/2018"
output: github_document
---

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)


devtools::install_github("thomasp85/patchwork")

```

```{r}
library(tidyverse)
```

```{r}

## This will round down each obervation down to the 1st of the month
## month = lubridate::floor_date(date, unit = "month"))
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```


## Start Grouping 
```{r}

## You can group by day, manth, or both 
weather_df %>% 
  group_by(name, month)
```

```{r}
## Adding sumarrize. In the middle you add what you want to rename it as

weather_df %>%
  group_by(month) %>%
  summarize(number = n())

## Group by the name 
weather_df %>%
  group_by(name) %>%
  summarize(number = n())
```

## Does the same thing!!!
```{r}
weather_df %>%
  count(month)
```

## Grouped Summaries 
```{r}

## Example in class 
weather_df %>%
  group_by(name, month) %>%
  summarize(number = n(),
            mean_tmax = mean(tmax))

## Remove missing values
weather_df %>%
  group_by(name, month) %>%
  summarize(number = n(),
            mean_tmax = mean(tmax, na.rm = TRUE))

weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n(),
            n_days = n_distinct(date))
```

This is still a tibble! 
```{r}
## na.rm takes away the missing data by default and you can also look at median, st dev
weather_df %>%
  group_by(month) %>%
  summarize(mean_tmax = mean(tmax),
            mean_prec = mean(prcp, na.rm = TRUE),
            median_tmax = median(tmax),
            sd_tmax = sd(tmax)) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point()

## Plot two tables at once...
## another way 
ggplot(weather_df, aes(x = month, y = mean_tmax, color = name)) + 
  geom_point(alpha = .5) + 
  geom_line(data = month, aes(x = month, y = mean_tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

Tidy is not always best for humans...
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  spread(key = month, value = mean_tmax) %>% 
  knitr::kable(digits = 1)
```

```{r}
## mutate is going to respect the grouping 
weather_df %>%
  group_by(name) %>%
  mutate(mean_tmax = mean(tmax, na.rm = TRUE))
```

More interesting example...
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(centered_tmax = tmax - mean(tmax)) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

## Window Functions

Use ranks
```{r}

## in class 

weather_df %>%
  group_by(name, month) %>%
  mutate(tmax_rank = min_rank(desc(tmax))) %>% 
  filter(tmax_rank < 2)
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  filter(min_rank(tmax) < 2)
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  filter(min_rank(desc(tmax)) < 4)
```

Use lags...
```{r}

## When using the lag fxn, make sure visits or dates are arranged sensibly
weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax))
```

## How neat is this? 
```{r}

## How much did the temp change from one day to the next 

weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax)) %>%
  summarize(temp_change_sd = sd(temp_change, na.rm = TRUE),
            temp_change_max = max(temp_change, na.rm = TRUE))
```

